spring:
  application:
    name: afisha
  datasource:
    url: jdbc:postgresql://localhost:5432/afisha?currentSchema=application
    password: terrrr
    username: postgres


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG